# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ae0fd214e3f99518ae9d43585565e3ceea9554fce2d2c17774be7050497c1cd17fa1e88de85df9a1c1afb925a9c2f886a10dfc4d09d57129a27541dc97a0b0e

test:
  secret_key_base: 72bfff784500fdf6aac20e4e631770c5d9480d5718ea0672c71867f1cbaf5e4eaa8dde8533e1a6b6c0cc51eeeab2b80f91c838146315652985e49f30f3209720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
